### ISSUE TITLE
Billing docs not mentioning limits

### ISSUE THREAD

**Issue by mambax** [swisscom/docs-appcloud-billing#1]
Hey

It would be interesting to know, why there is a 3 org restriction on the billing accounts. Also if it can be raised or how people can bypass this restriction because the only way around appears to me to create numbered billing accounts "Account 1", "Account 2"... which use the same credit card which is - yeah - let's say ugly.

Any info would be appreciated!

Thanks und schöne zeme ;)

**Comment by nicregez** [comment]
Hey Mambax

Thanks for reaching out. You can contact us via [support page](https://developer.swisscom.com/support), mention the customer number of your billing account and tell us the number of orgs you would like to be able to create. We will check your request and raise the limit of your account.

Best regards
Swisscom Application Cloud

**Comment by annaronco** [comment]
Thank you @mambax for the hint. The information was added to the documentation cda3ff8
