### ISSUE TITLE
Change billing account of org

### ISSUE THREAD

**Issue by mambax** [swisscom/docs-appcloud-billing#2]
Me again

Could you also add some words how (if) to change the billing account of an org?

Thanks

**Comment by nicregez** [comment]
Hello Mambax

It is not possible to transfer an org from one billing account to another billing account. Instead, you need to delete it and re-create a new org under the target account.

Best regards
Swisscom Application Cloud

**Comment by annaronco** [comment]
Thank you @mambax for the hint. The information was added to the documentation https://github.com/swisscom/docs-appcloud-billing/commit/cda3ff8ffe79bdc1ead984f0941f3c8764b22d69
